---
- name: allow http,dhcp,tftp services in firewall
  firewalld:
          service: "{{ item }}"
          permanent: yes
          state: enabled
  loop:
          - http
          - dhcp
- firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
  loop:
          - 69/tcp
          - 69/udp
- name: restart firewall
  service:
          name: firewalld
          state: restarted
